# Generated by Django 5.1.2 on 2024-11-01 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_personalinfo_description_about_me_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.skillcategory'),
        ),
    ]
