# Generated by Django 5.1.2 on 2024-11-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_education_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinecourse',
            name='description',
        ),
        migrations.AddField(
            model_name='onlinecourse',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
