# Generated by Django 5.1.2 on 2024-11-01 16:26

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='main_image',
            field=models.ImageField(upload_to=core.models.upload_to),
        ),
    ]
