# Generated by Django 5.1.2 on 2024-11-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_personalinfo_facebook_personalinfo_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='Base/background'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='myimg',
            field=models.ImageField(blank=True, null=True, upload_to='Base/myimg'),
        ),
    ]
