# Generated by Django 5.1.2 on 2024-11-02 17:37

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_personalinfo_background_personalinfo_myimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='my_resume',
            field=models.FileField(blank=True, null=True, upload_to='my_resume'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.background_upload_to),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='myimg',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.my_img_upload_to),
        ),
    ]
